let MoviesList = [
  {
    id:1,
    src: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/pichaikkaran-2-et00324847-1683542091.jpg",
    star: <i class="bi bi-star-fill"></i>,
    ratings: "7.5/10",
    votes: "7.6K votes",
    name: "Pichaikkaran-2",
    genre: "Action/Thriller",
  },
  {
    id:2,
    src: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/fast-x-et00122562-1683110461.jpg",
    star: <i class="bi bi-star-fill"></i>,
    ratings: "7.5/10",
    votes: "7.6K votes",
    name: "Fast-X",
    genre: "Action/Adventure/Crime/Thriller",
  },
  {
    id:3,
    src: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/good-night-et00358164-1682501014.jpg",
    star: <i class="bi bi-star-fill"></i>,
    ratings: "7.5/10",
    votes: "7.6K votes",
    name: "Good-Night",
    genre: "Comedy/Drama/Family",
  },
  {
    id:4,
    src: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/ponniyin-selvan--part-2-et00348725-1680776467.jpg",
    star: <i class="bi bi-star-fill"></i>,
    ratings: "7.5/10",
    votes: "7.6K votes",
    name: "Ponniyin-Selvan-Part 2",
    genre: "Action/Adventure/Drama/Historical",
  },
  {
    id:5,
    src: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/vinnaithaandi-varuvaayaa-et00038721-06-11-2020-11-54-16.jpg",
    star: <i class="bi bi-star-fill"></i>,
    ratings: "7.5/10",
    votes: "7.6K votes",
    name: "Vinnaithaandi-Varuvaayaa",
    genre: "Romance/Drama",
  },
  {
    id:6,
    src: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/the-little-mermaid-et00058086-1678711953.jpg",
    star: <i class="bi bi-star-fill"></i>,
    ratings: "7.5/10",
    votes: "7.6K votes",
    name: "The Little Mermaid",
    genre: "Adventure/Family/Fantasy",
  },
  {
    id:7,
    src: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/guardians-of-the-galaxy-vol-3-et00310794-1683529214.jpg",
    star: <i class="bi bi-star-fill"></i>,
    ratings: "7.5/10",
    votes: "7.6K votes",
    name: "Guardians of the Galaxy Vol. 3",
    genre: "Action/Adventure/Comedy/Sci-Fi",
  },
  {
    id:8,
  src: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/ib71-et00312966-1683884508.jpg",
  star: <i class="bi bi-star-fill"></i>,
  ratings: "7.5/10",
  votes: "7.6K votes",
  name: "IB71",
  genre: "Action/Period/Thriller",
  },
];
export default MoviesList;
